name: Build 1.18.x

on:
  push:
    tags:
      - 'v*'

jobs:
  main:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Get Version
      id: version
      uses: actions/github-script@0.4.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        result-encoding: string
        script: |
          let ref = '${{ github.ref }}';
          return ref.startsWith('refs/tags/v') ? ref.replace('refs/tags/v', '') : 'indev';
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
      env:
        VERSION: ${{ steps.version.outputs.result }}
    - name: Publish
      id: publish
      if: ${{ steps.version_type.outputs.result != 'alpha' && success() }}
      uses: gradle/gradle-build-action@v2
      with:
        arguments: curseforge
      env:
        VERSION: ${{ steps.version.outputs.result }}
        CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
